name: output the name of the branch to test
on:
  workflow_dispatch:

jobs:
  output-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
        id: extract_branch
      - name: output
        shell: bash
        run: echo $BRANCH_NAME
